name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 源码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      # 2. Setup Ruby & Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Jekyll
        run: |
          gem install bundler
          bundle install

      # 3. Build 主站 (生成到 _site_main 临时目录)
      - name: Build Jekyll site
        run: bundle exec jekyll build -d _site_main

      # 4. 合并主站和 HOI-Dyn 子站
      - name: Prepare final _site
        run: |
          rm -rf _site
          mkdir -p _site
          cp -a _site_main/. _site/
          cp -r projects/* _site/
          rm -rf _site/projects
          rm -rf _site_main


      # 5. 部署到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
          publish_branch: gh-pages
          keep_files: false
