name: Deploy HOI-Dyn Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 仓库，不拉 submodule
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    # 2. Deploy HOI-Dyn 到 gh-pages 的 hoi-dyn 目录
    - name: Deploy HOI-Dyn Website
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./projects/hoi-dyn      # 本地网页文件夹
        publish_branch: gh-pages             # 发布到 gh-pages 分支
        destination_dir: hoi-dyn             # 部署到 gh-pages 根目录下的 hoi-dyn 文件夹
