name: Deploy HOI-Dyn Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 仓库
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: Deploy HOI-Dyn Website
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./projects/hoi-dyn
        publish_branch: gh-pages
        destination_dir: hoi-dyn
        keep_files: true                     # 保留 gh-pages 分支原有文件
