name: Get Citation Data

# 触发条件：push main、定时、手动
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'  # 每天 UTC 8:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout 仓库
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    # 2. 安装 Python 依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools
        pip3 install --upgrade pip

    # 3. 运行抓取脚本
    - name: Run Google Scholar Crawler
      run: |
        cd google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        cd ../google_scholar_crawler/results
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:google-scholar-stats --force
      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
